// Which Title this app talks to, and in which environment. Always targets the real backend
// (https://api.idosgames.com).
//
// ⚠ PLATFORM-OWNED. The platform's build packs its own copy of this file over the project's (the
// same way it regenerates src/idos.title.ts), so an edit here never reaches a published game.
//
// Neither IDENTITY nor ENVIRONMENT is read from the link (query or path) — that is the point. A link
// is something anyone can edit: when `?titleID=` could pick the title, another publisher could open
// this finished game with their own title in the link and run it on their title's settings.
//
//   identity — WHICH game. Resolved once, in this order:
//     1. src/idos.title.ts   — the centralized identity file (generated by the platform, or filled
//                              by hand on a manual scaffold). Wins over everything, and is the only
//                              channel a packaged mobile build has.
//     2. the host            — {id}.idos.games / {id}-dev.idos.games, the title's own addresses. The
//                              platform's game host serves those names with that title's files only.
//     3. VITE_IDOS_TITLE_ID  — local development, via .env.local.
//   There is deliberately NO fallback title. A build that cannot tell which game it is must fail
//   loudly rather than quietly sign in to somebody else's data.
//
//   environment — WHICH copy of that game, prod or dev. A modifier on the identity, never a
//   different identity: the dev title is always `{id}-DEV`. Resolved in this order:
//     1. the host            — {id}-dev.idos.games is dev, {id}.idos.games is prod. That is how one
//                              artifact runs on both without a rebuild.
//     2. the live preview    — the AI Coder's in-browser preview marks its sandbox as dev before
//                              any project code runs (it lives on a foreign origin, so the host
//                              cannot say it).
//     3. VITE_IDOS_ENV       — local development, via .env.local ("dev" or "prod").
//     4. IDOS_DEFAULT_ENV    — the baked default from src/idos.title.ts.

import { IDOS_BUILD_KEY, IDOS_DEFAULT_ENV, IDOS_TITLE_ID } from "./idos.title";

/** Mirrors DevTitleService.DevSuffix on the backend. */
const DEV_SUFFIX = "-DEV";

// Build-time values straight from Vite's `import.meta.env` (VITE_* of .env.local), not through
// ./env: this file is packed over the project's own at build time, so it must not depend on what
// the project's other files export — nor on the project having Vite's client types, hence the cast.
const viteEnv: Record<string, string | undefined> =
  (import.meta as unknown as { env?: Record<string, string | undefined> })
    .env ?? {};
const buildEnv = {
  TITLE_ID: viteEnv.VITE_IDOS_TITLE_ID,
  BUILD_KEY: viteEnv.VITE_IDOS_BUILD_KEY,
  ENV: viteEnv.VITE_IDOS_ENV,
};

/**
 * The title's own addresses: `{titleid}.idos.games` (prod) and `{titleid}-dev.idos.games` (dev).
 * Title ids are 8 characters of [A-Z0-9] and hostnames are case-insensitive, so the lowercase id IS
 * the address. Mirrors the platform's game-host Worker (TitleHostWorker/src/host.ts). A publisher's
 * own domain carries no id — that is what idos.title.ts is for.
 */
function fromHost(): { titleId: string; dev: boolean } | null {
  if (typeof window === "undefined") return null;
  const match = window.location.hostname
    .toLowerCase()
    .replace(/\.$/, "")
    .match(/^([a-z0-9]{8})(-dev)?\.idos\.games$/);
  const id = match?.[1];
  return id
    ? { titleId: id.toUpperCase(), dev: match?.[2] !== undefined }
    : null;
}

/**
 * Set by the AI Coder's live preview before any project code runs. Nothing outside the platform can
 * set it on a hosted game: that page is served from the title's own origin, and a script from
 * anywhere else cannot reach its globals.
 */
function previewEnv(): string | null {
  const marker = (globalThis as { __IDOS_PREVIEW__?: { env?: unknown } })
    .__IDOS_PREVIEW__;
  return typeof marker?.env === "string" ? marker.env : null;
}

const host = fromHost();
const envTitle = buildEnv.TITLE_ID ?? "";
const envTitleIsDev = envTitle.endsWith(DEV_SUFFIX);

const canonicalTitle =
  IDOS_TITLE_ID ||
  host?.titleId ||
  (envTitleIsDev ? envTitle.slice(0, -DEV_SUFFIX.length) : envTitle);

if (!canonicalTitle) {
  throw new Error(
    "[idos] No Title id resolved. Expected src/idos.title.ts (generated by the platform), " +
      "a {titleid}.idos.games host, or VITE_IDOS_TITLE_ID in .env.local.",
  );
}

function resolveIsDev(): boolean {
  if (host) return host.dev;
  const preview = previewEnv();
  if (preview !== null) return preview === "dev";
  if (buildEnv.ENV === "dev" || buildEnv.ENV === "prod")
    return buildEnv.ENV === "dev";
  if (envTitleIsDev) return true;
  return IDOS_DEFAULT_ENV === "dev";
}

export const TITLE_ID = resolveIsDev()
  ? `${canonicalTitle}${DEV_SUFFIX}`
  : canonicalTitle;

export const BUILD_KEY = IDOS_BUILD_KEY || buildEnv.BUILD_KEY || "";
